[package]
name = "jump-frame-trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }

rdev = "0.5"
gilrs = "0.10"
rodio = "0.17"

[build-dependencies]
tauri-build = { version = "2", features = [] }
